export const BadgeList = [
  { key: 'cannon_arm', label: 'Cannon Arm', icon: '💪' },
  { key: 'deep_ball', label: 'Deep Ball', icon: '🎯' },
  { key: 'quick_release', label: 'Quick Release', icon: '⚡️' },
  { key: 'field_general', label: 'Field General', icon: '🧠' },
  { key: 'dual_threat', label: 'Dual Threat', icon: '🏃' },
  { key: 'pocket_presence', label: 'Pocket Presence', icon: '🛡️' },
  { key: 'clutch', label: 'Clutch', icon: '❄️' },
  { key: 'comeback_kid', label: 'Comeback Kid', icon: '🔄' },
  { key: 'improviser', label: 'Improviser', icon: '🎭' },
  { key: 'leader', label: 'Leader', icon: '👑' },
  { key: 'iron_man', label: 'Iron Man', icon: '🦾' },
  { key: 'game_manager', label: 'Game Manager', icon: '🎮' },
  { key: 'touch_passer', label: 'Touch Passer', icon: '🪶' },
  { key: 'red_zone_threat', label: 'Red Zone Threat', icon: '🎯' },
  { key: 'scrambler', label: 'Scrambler', icon: '💨' },
];
