export const TEAM_LOGO_MAP = {
  // NFL team abbreviations to logo filenames
  ARI: 'cardinals',
  ATL: 'falcons',
  BAL: 'ravens',
  BUF: 'bills',
  CAR: 'panthers',
  CHI: 'bears',
  CIN: 'bengals',
  CLE: 'browns',
  DAL: 'cowboys',
  DEN: 'broncos',
  DET: 'lions',
  GB: 'packers',
  HOU: 'texans',
  IND: 'colts',
  JAX: 'jaguars',
  KC: 'chiefs',
  LAC: 'chargers',
  LAR: 'rams',
  LV: 'raiders',
  MIA: 'dolphins',
  MIN: 'vikings',
  NE: 'patriots',
  NO: 'saints',
  NYG: 'giants',
  NYJ: 'jets',
  PHI: 'eagles',
  PIT: 'steelers',
  SEA: 'seahawks',
  SF: '49ers',
  TB: 'buccaneers',
  TEN: 'titans',
  WAS: 'commanders',
  
  // Full team names
  'Arizona Cardinals': 'cardinals',
  'Atlanta Falcons': 'falcons',
  'Baltimore Ravens': 'ravens',
  'Buffalo Bills': 'bills',
  'Carolina Panthers': 'panthers',
  'Chicago Bears': 'bears',
  'Cincinnati Bengals': 'bengals',
  'Cleveland Browns': 'browns',
  'Dallas Cowboys': 'cowboys',
  'Denver Broncos': 'broncos',
  'Detroit Lions': 'lions',
  'Green Bay Packers': 'packers',
  'Houston Texans': 'texans',
  'Indianapolis Colts': 'colts',
  'Jacksonville Jaguars': 'jaguars',
  'Kansas City Chiefs': 'chiefs',
  'Los Angeles Chargers': 'chargers',
  'Los Angeles Rams': 'rams',
  'Las Vegas Raiders': 'raiders',
  'Miami Dolphins': 'dolphins',
  'Minnesota Vikings': 'vikings',
  'New England Patriots': 'patriots',
  'New Orleans Saints': 'saints',
  'New York Giants': 'giants',
  'New York Jets': 'jets',
  'Philadelphia Eagles': 'eagles',
  'Pittsburgh Steelers': 'steelers',
  'Seattle Seahawks': 'seahawks',
  'San Francisco 49ers': '49ers',
  'Tampa Bay Buccaneers': 'buccaneers',
  'Tennessee Titans': 'titans',
  'Washington Commanders': 'commanders',
  
  // Short names
  Cardinals: 'cardinals',
  Falcons: 'falcons',
  Ravens: 'ravens',
  Bills: 'bills',
  Panthers: 'panthers',
  Bears: 'bears',
  Bengals: 'bengals',
  Browns: 'browns',
  Cowboys: 'cowboys',
  Broncos: 'broncos',
  Lions: 'lions',
  Packers: 'packers',
  Texans: 'texans',
  Colts: 'colts',
  Jaguars: 'jaguars',
  Chiefs: 'chiefs',
  Chargers: 'chargers',
  Rams: 'rams',
  Raiders: 'raiders',
  Dolphins: 'dolphins',
  Vikings: 'vikings',
  Patriots: 'patriots',
  Saints: 'saints',
  Giants: 'giants',
  Jets: 'jets',
  Eagles: 'eagles',
  Steelers: 'steelers',
  Seahawks: 'seahawks',
  '49ers': '49ers',
  Buccaneers: 'buccaneers',
  Titans: 'titans',
  Commanders: 'commanders',
};

export function getTeamLogoFilename(teamName) {
  if (!teamName) return 'default';
  return TEAM_LOGO_MAP[teamName] || teamName.toLowerCase().replace(/\s+/g, '');
}
